# -*- coding: utf-8 -*-
"""basic ai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qwt6vyuRSbWw4CMPQ4v04VUEG3D8K5Fv

การนำเข้าข้อมูล (Load Datasets)
"""

from sklearn import datasets
digits = datasets.load_digits()
print(digits)

"""แบ่งข้อมูลเป็น x,y"""

x = digits.data
y = digits.target

"""plot image of MNIST dataset"""

print(x[0])

import numpy as np
import matplotlib.pyplot as plt

plt.imshow(np.reshape(x[0], (8,8)), cmap = plt.cm.magma)
plt.show()

"""train and test

"""

#split data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

#train model
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(x_train,y_train)

"""model Evaluation"""

#accuracy
acc = LR.score(x_test, y_test)
print(acc*100)
print(round(acc*100,2))
print('Accuracy =', round(acc*100,2))

#confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = LR.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

#plot cm
import seaborn as sns

plt.figure(figsize = (9,9))
sns.heatmap(cm, annot=True, linewidths=1, cmap='PuBuGn_r')
plt.ylabel('y_pred')
plt.xlabel('y_test')
figure_title = 'accuracy = {0}'.format(acc)
plt.title(figure_title, size=15)